### ISSUE TITLE
Landing Page Sections

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#112]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="15%"/></p>

> Associated epics: #63

This issue documents the implementation of all landing page sections including required dependencies, components and illustrations.

## Hero

The first section will be the “hero” of the landing page that renders a short project description and the animated SVG component [Arctic Landscape][gh-al]. The animation will be triggered through the [React Waypoint][gh-rw] project.

## Color Palettes

The 2nd and 3rd sections will be about Nord's color palettes and they will provide information about the modularity and contrast. All palettes will be visualized through a new "color palette card" component that'll consist of the actual color as small, rounded boxes and the associated color code as label using the hexadecimal format.

## “Nordify”

The 4th section will present Nord's port projects which can be used to “nordify” the favorite apps and platforms of the users. It'll consist of the text content as well as a new illustration that might also be animated later on using a 3D parallax effect that renders based on the current mouse position in the section.

## Color Swatches

The 5th section will be about Nord's “native” color swatches. It will consist of the same elements like the 4th section, but will render a new non-animated illustration showing a application UI with Nord loaded as color palette.

## Syntax Highlighting

The 6th section will be all about Nord's features to highlight code. Next to the text content and summary it will also render a new and animated illustration.

## Community

The 7th and also last section will present details about Nord's communities. It will render the animated [Arctic Ocean Fractal][gh-aof] component and a short summary about how to join and being part of the Nord community.

## Responsive Design

All sections will follow the [responsive design concept][gh-52] to adjust the rendered content based on the available width and provide an optimal UX on smaller viewports.

## Tasks

- [x] Install required packages:
  - [arctic-landscape][npm-al]
  - [arctic-ocean-fractal][npm-aof]
  - [react-waypoint][npm-rwp]
- [x] Implement base HTML components for the `<pre>` and `<code>` elements.
- [x] Implement new wave and line vector divider components.
- [x] Implement utility function to manage section IDs per route.
- [x] Implement core atom component to represent a color palette.
- [x] Implement molecule component to represent a feature side-by-side (vertical/horizontal) through text content and a visualization.
- [x] Create illustrations for the “Nordify” (port projects) and “Color Swatches” sections.
- [x] Implement main organism components for all sections.

[gh-52]: https://github.com/arcticicestudio/nord-docs/issues/52
[gh-al]: https://github.com/arcticicestudio/arctic-landscape
[gh-aof]: https://www.npmjs.com/package/arctic-ocean-fractal
[gh-rw]: https://github.com/brigade/react-waypoint
[npm-al]: https://www.npmjs.com/package/arctic-landscape
[npm-aof]: https://www.npmjs.com/package/arctic-ocean-fractal
[npm-rwp]: https://www.npmjs.com/package/react-waypoint
