### ISSUE TITLE
Community Page Sections

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#115]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="15%"/></p>

> Associated epic: #63

This issue documents the implementation of all community page sections including required dependencies, components and illustrations.

## Hero

The first section will be the “hero” of the community page that renders a description about the page's purpose and an animated SVG component.

## Chats

The 2nd section will be about Nord's community chats where each platform is represented as card rendered in a two-column grid layout. Each card will contain the platforms official logo, colorized with colors of the respective brand guidelines, a short summary about the platform/service and a link component that'll forward to the community within the platform.
Next to the official main channel each platform also provides sub-channels for  all port projects

As of now the following community chats of Nord are planned to be represented:

- Arctic Ice Studio's official community on [Spectrum][ct-spec]
- Nord's official [Keybase team chat][ct-kb]
- Nord's official [Slack][ct-sl] workspace
- Nord's official [Discord][] space

## Content

The 3th and also last section present platforms where the community can create content and ask questions for and about Nord. Next to the official documentation these are knowledge bases also powered by community. Like the chat platforms in the previous section each platform/service will be represented as card including the same information, rendered by the same components, and also structured in a two-column grid layout.
Next to this, each card will include the latest three items (questions, posts etc.) of the platform's community rendered as link component with the item's title and metadata like tags, the name of the author and the relative creation date/time.

As of now the following community platforms of Nord are planned to be represented:

- Latest questions from [Stack Overflow][cnt-stof] tagged with `nord` or `nordtheme`
- Nord's official [/r/nordtheme][cnt-r] subreddit

All data will be fetched from the official REST APIs from the respective platform using the [axios][gh-ax] client. The processing of any date/time data will be handled with [date-fns][gh-dfn], a modern and more lightweight ES6+ library with tree-shaking support that'll be used project-wide for Nord Docs to handle any other date/time data like e.g. blog posts metadata.

## Responsive Design

All sections will follow the [responsive design concept][gh-52] to adjust the rendered content based on the available width and provide an optimal UX on smaller viewports.

## Tasks

- [ ] Install required packages:
  - [axios][npm-ax]
  - [date-fns][npm-dfn]
- [ ] Implement base HTML components for the `<hr>` element.
- [ ] Implement utility function to decode numeric HTML entities.
- [ ] Create illustration SVG components for the “Hero” section.
- [ ] Create new SVG vector section divider components.
- [ ] Change `FeatureDuo` landing page molecule to be a shared page component.
- [ ] Implement main organism components for all sections.

[cnt-r]: https://www.reddit.com/r/nordtheme
[cnt-stof]: https://stackoverflow.com/questions/tagged/nord+or+nordtheme
[ct-kb]: https://keybase.io/team/nord.chat
[ct-sl]: https://arcticicestudio.slack.com
[ct-spec]: https://spectrum.chat/arcticicestudio
[discord]: https://discordapp.com
[gh-52]: https://github.com/arcticicestudio/nord-docs/issues/52
[gh-ax]: https://github.com/axios/axios
[gh-dfn]: https://github.com/date-fns/date-fns
[npm-al]: https://www.npmjs.com/package/axios
[npm-dfn]: https://www.npmjs.com/package/date-fns
