### ISSUE TITLE
Docs Page Sections

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#117]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="15%"/></p>

> Associated epic: #63

This issue documents the implementation of all docs page sections including required changes to other components.

## Hero

The first section will be the “hero” of the docs page that renders a description about the page's purpose.

## Contents Cards

The 2nd section will be about Nord's documentation contents where each category is represented as card rendered in a two-column grid layout. Each card will contain a topic icon, colorized with a accent color from Nord's palettes and a short summary about the topic's links.

As of now a “Getting Started” and “References” category are planned to be represented.

## Responsive Design

All sections will follow the [responsive design concept][gh-52] to adjust the rendered content based on the available width and provide an optimal UX on smaller viewports.

## Tasks

- [ ] Implement style variants for core `Header` component to match current page.
- [ ] Implement more icon components for contents cards.
- [ ] Implement main organism components for all sections.

[gh-52]: https://github.com/arcticicestudio/nord-docs/issues/52
