### ISSUE TITLE
Ports Page Sections

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#119]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="15%"/></p>

> Associated epic: #63
> Depends on: #123, #125

This issue documents the implementation of all `/ports` page sections including required changes to involved components and new dependencies.

> :construction: **This document is _work in progress_ which means it is not completed yet and will be extended!**

## Hero

The first section will contain a _feature duo_ container with the pages heading and a summary about Nord's ports.
Underneath the static vector graphic that is currently placed in the port section of the landing (`/`) page will be implemented as interactive animated component. It will use a 3D depth effect for the port project's logos by moving against the direction of the current mouse position where the larger logos will move more to give the impression that they are closer.

## Grid Filter

The second section will consist of a input field that allows users to filter available port projects by predefined search terms. Underneath a animated grid of card components will react to the input field by filtering non-matching ports projects.
Each card represents one port project and will consist of the logo, the name (with the _Nord_ prefix) as well as a card footer that contains the version of the latest release of the respective project and the number of stars of the GitHub repository.

To prevent UI freezes/frame drops when users typing in the input field while the grid reacts to the change immediately a _debounce_ might be used. It can wait some milliseconds before actually filtering the grid by the given search term. To get the best performance [Lodash][] can be used through [gatsby-plugin-lodash][gh-gpld] which sets up [babel-plugin-lodash][gh-bpl] and [lodash-webpack-plugin][gh-wppl].

## GitHub GraphQL API

To view the metadata about the port project repositories [Gatsby's fantastic GraphQL integration][gbd-gql] will be used through the awesome [gatsby-source-graphql][gh-gbsgql] plugin. It allows to fire queries that 'll get executed and stitches remote schemas together by adding a type that wraps the remote schema Query type and putting it under field of Gatsby GraphQL Query.

## Interactive Animations

To implement components with an interactive animation the awesome [react-spring][] project will be used which allows, like the fantastic and also already used [react-pose][] library, to use spring-physics based animations.
The advantage of react-spring is that it bails out of the React renderer to avoid unnecessary renders and instead uses native methods to get the best performance even for complex animations.
It comes with [first-class support for Hooks][rspd-h], a great and extensive documentation and [a lot of examples for inspirations][rspd-ex].

## Responsive Design

All sections will follow the [responsive design concept][gh-52] to adjust the rendered content based on the available width and provide an optimal UX on smaller viewports.

## Tasks

- [x] Install dependencies:
  - [gatsby-plugin-lodash][npm-gpl]
  - [gatsby-source-graphql][npm-gbsgql]
  - [lodash-webpack-plugin][npm-wppl]
  - [react-spring][npm-rs]
- [x] Configure Gatsby GraphQL source plugin.
- [x] Configure Gatsby Lodash plugin.
- [x] Implement port project metadata provider hook via static query for GitHub GraphQL API and static data.
- [x] Implement new SVG components for logos and section dividers.
- [x] Implement interactive and animated port project SVG illustration component.
- [x] Implement hero and card grid filter section components.
- [x] Implement initial pages for each currently existing port projects showing a empty state and link to refer to the GitHub repository for the meantime the pages are not implemented yet.

[gh-bpl]: https://github.com/lodash/babel-plugin-lodash
[gbd-gql]: https://www.gatsbyjs.org/docs/querying-with-graphql
[gh-52]: https://github.com/arcticicestudio/nord-docs/issues/52
[gh-gbsgql]: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql
[gh-gpld]: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-lodash
[gh-wppl]: https://github.com/lodash/lodash-webpack-plugin
[lodash]: https://lodash.com
[npm-gbsgql]: https://www.npmjs.com/package/gatsby-source-graphql
[npm-gpl]: https://www.npmjs.com/package/gatsby-plugin-lodash
[npm-rs]: https://www.npmjs.com/package/react-spring
[npm-wppl]: https://www.npmjs.com/package/lodash-webpack-plugin
[react-pose]: https://popmotion.io/pose
[react-spring]: https://www.react-spring.io
[rspd-ex]: https://www.react-spring.io/docs/hooks/examples
[rspd-h]: https://www.react-spring.io/docs/hooks/basics
