### ISSUE TITLE
React Hooks Support

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#121]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/52519841-ee1f7680-2c61-11e9-91fa-b7e41ab30145.png" /></p>

Since the [latest stable React version finally comes with the long-awaited Hooks][r-b-16.8.0] the project will add support for the new features.
To simplify the usage and import of [custom Hooks][r-d-ch] a new `hooks` import alias will be added that allows to import custom hooks from a new `src/hooks` Hooks base directory.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48658871-4707b600-ea49-11e8-8a08-39e1a318c442.png" /></p>

The ESLint plugin [eslint-plugin-react-hooks][npm-esl-rh] provided by the React core team will be added to enforce the [rules of Hooks][r-d-roh]. This is a temporary integration until [eslint-config-arcticicestudio][gh-esl-c-ais] has been updated to support and include the plugin.

The plugin will be configured by following the [official documentation about the rules of Hooks][r-d-roh].
Since React Hooks are making use of inline arrow functions the [react/jsx-no-bind][esl-r-jsx-no-bind] rule will be disabled to avoid noisy false-positive errors.

### Tasks

- [x] Install development dependencies:
  - [eslint-plugin-react-hooks][npm-esl-rh]
- [x] Add new `hooks` import alias for the new `src/hooks` Hooks base directory
- [x] Configure the new ESLint plugin
  - Enable new `react-hooks/rules-of-hooks` rule(s) with `error` scope
  - Disable conflicting `react/jsx-no-bind` rule

[esl-r-jsx-no-bind]: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md
[gh-esl-c-ais]: https://github.com/arcticicestudio/eslint-config-arcticicestudio
[npm-esl-rh]: https://www.npmjs.com/package/eslint-plugin-react-hooks
[r-b-16.8.0]: https://reactjs.org/blog/2019/02/06/react-v16.8.0.html
[r-d-ch]: https://reactjs.org/docs/hooks-custom.html
[r-d-roh]: https://reactjs.org/docs/hooks-rules.html
