### ISSUE TITLE
MDX Integration for docs and blog pages

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#129]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="15%"/></p>

> Associated epic: #24, #63, #69

This issue documents the integration of [MDX][] with [gatsby-mdx] to implement the logic and layout for `/docs` and `/blog` pages.

> :construction: **This document is _work in progress_ which means it is not completed yet and will be extended!**

## Responsive Design

All sections will follow the [responsive design concept][gh-52] to adjust the rendered content based on the available width and provide an optimal UX on smaller viewports.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48661214-dffcf800-ea6e-11e8-9ee4-939756439f1e.png" /></p>

## MDX

This issue handles the actual content of the documentation and blog posts.
Gatsby allows to use Markdown for it that comes with the nice side effect that the already existing documentations can simply be adapted and reused, but unfortunately it is limited to it's reduced and simplified syntax.

To also use the great power of React for content and not only layout and design this project will make use of the [MDX specification][gh-mdx-spec], a new language and abstract syntax tree definition.

> In order to ensure a vibrant ecosystem and community, tooling needs to exist for formatting, linting, and plugins. This tooling requires a foundational specification and abstract syntax tree so that parsing is properly handled before transforming to JSX/Hyperscript/React/etc and potentially leveraging existing plugin ecosystems.

We will use the official implementation, the [fully-featured MDX parser, loader and JSX renderer][mdx] together with the great Gatsby plugin [gatsby-mdx][] to allow to seamlessly use JSX in Markdown documents by importing components and export metadata or any other ECMAScript compliant data structures like _frontmatter_.

> - 💻 **Everything is a component**: Use existing components inside your MDX and import other MDX files as plain components.
> - 🔧 **Customizable**: Decide which component is rendered for each Markdown element ({ h1: MyHeading }).
> - 📚 **Markdown-based**: The simplicity and elegance of Markdown remains, you interleave JSX only when you want to.
> - 🔥 **Blazingly blazing fast**: MDX has no runtime, all compilation occurs during the build stage.

More details are provided by the [official MDX][mdx] and [gatsby-mdx][] websites that include docs to get started, usage examples and advanced configuration and customization information.

### Integration

To integrate MDX Gatsby's [`onCreateNode`][gatsby-docs-oncreatenode] and [`createPages`][gatsby-docs-createpages] APIs will be implemented to handle the generation of the GraphQL MDX nodes and the subsequent automated creation of the docs pages and blog posts.

## Images

To get the [best performance and quality for images][gatsby-docs-images] the awesome Gatsby's awesome support for the [high performance Node.js image processing library “Sharp“][gh-sharp] will be used through [`gatsby-plugin-sharp`][gh-gatsby-p-sharp], [`gatsby-transformer-sharp`][gh-gatsby-t-sharp] and [gatsby-image][gh-gatsby-image].

To automatically process all images the transformer provides GraphQL query fragments like `GatsbyImageSharpFluid`. They will be used within custom fragments that'll be implemented to fit the project structure.

## Content Components

In order to create great documentations and blog posts with interactive elements a new `mdx-elements` atom core package will be created initially including some custom React components that can be imported and placed in MDX based content.

To reduce the requirement of imports and "logical Markdown" almost all HTML elements supported by the official Markdown as well as the [GitHub Flavored Markdown Specification][gfm] the [`MDXProvider`][mdx-docs-prov] component will be used to map the project's base components to their specific HTML elements.

## Blog Posts

The last remaining main page is `/blog` which will present an overview of Nord's blog posts in a three-column grid of card components sorted descending by their publish date. Each card will consist of an cover image together with the title of the post. The latest post will span over two columns at the top for a nice visual structure and better recognizability.
While a one-column card will use a cover image the latest post will use a _banner_ that will either be the same image with a larger width, a variant of it or a completly different one.

A blog post itself will make use of the MDX features and the custom MDX components mentioned in the paragraph above. To simplify the usage of the _cover_ and _banner_ image they will be processed with Gatsby's [`onCreateNode`][gatsby-docs-oncreatenode] API in combination with [Gatsby's `mapping` configuration feature][gatsby-docs-conf-mapping]. This allows to map the paths to the images to a `File` node that will then be handled by the [Gatsby image processing plugin workflow][gatsby-docs-images] also documented in the [Images](#images) section above.

Another required node will be the `heroImage` field that queries for a `hero.(png|jpg|jpeg)` image that'll be used as the hero of a blog post.
To allow to also use videos in blog posts or even as header a custom `Video` MDX component will be implemented including the optional `heroVideo` and `heroVideoPoster` GraphQL node fields.

All together that results in the following required and optional images/videos mapped to specific node fields with **reserved file names per blog post directory** for simple usage via GraphQL queries:

- `bannerImage` ↹ `banner.(png|jpg|jpeg)` — The **required** banner image of a blog post card (used when currently the latest two-column wide post placed on top of the grid).
- `coverImage` ↹ `cover.(png|jpg|jpeg)` — The **required** cover image of a one-column blog post.
- `heroImage` ↹ `hero.(png|jpg|jpeg)` — The **required** hero image of a blog post.
- `heroVideo` ↹ `hero.(mp4|webm)` — The **optional** hero video of a blog post.
- `heroVideoPoster` ↹ `heroposter.(png|jpg|jpeg)` — The **optional** poster image of a blog post `heroVideo`.

### Known Problems

To prevent the [`unknwon field` GraphQL error during build time][gatsbyjs/gatsby#3344] (e.g. when there are no blog posts yet) a _dummy_/_placeholder_ blog post and docs page will be created.
Anyway, this will be removed as soon as there is finally the first blog post and docs page. Later on the project will migrate to the shiny [new schema customization API][gatsby-blog-custom-schemes].

## Tasks

- [x] Install dependencies:
  - [@babel/polyfill][npm-bb-poly]
  - [@mdx-js/tag][npm-mdx-tag]
  - [camelcase][npm-cc]
  - [gatsby-image][npm-gat-img]
  - [gatsby-mdx][npm-gat-mdx]
  - [gatsby-plugin-sharp][npm-gat-p-shp]
  - [gatsby-transformer-sharp][npm-gat-t-shp]
- [x] Install development dependencies:
  - [rehype-slug][npm-rh-slug]
  - [remark-breaks][npm-rm-br]
  - [remark-github][npm-rm-gh]
  - [@mdx-js/mdx][npm-mdx]
  - [glob][npm-glob]
- [x] Implement Gatsby `onCreateNode` and `createPages` APIs.
- [x] Configure `gatsby-plugin-sharp`, `gatsby-transformer-sharp` and `gatsby-mdx` including custom GraphQL fragments with the `GatsbyImageSharpFluid` type.
- [x] Rename `HTMLElements` package to `html-elements` to reflect its purpose as package and not as a React component.
- [x] Initially implement MDX-specific components `Image` (wraps `GatsbyImage`), `ShinkWidth` and `Video` placed in the new atom core package `mdx-elements`.
- [x] Implement `DocsPage` and `BlogPost` template components
  - Implement `PaperSheet` styled component for uniform docs design
  - Use `MDXProvider` to map custom HTML components to default Markdown elements
  - Implement wrapper component for doc pages to define specific style like _Inter UI_ font family.
- [x] Implement blog post grid and card components including the corresponsing GraphQL node fields and queries.

[gatsby-blog-custom-schemes]: https://www.gatsbyjs.org/blog/2019-03-04-new-schema-customization
[gatsby-docs-conf-mapping]: https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types
[gatsby-docs-createpages]: https://www.gatsbyjs.org/docs/node-apis/#createPages
[gatsby-docs-images]: https://www.gatsbyjs.org/docs/working-with-images
[gatsby-docs-oncreatenode]: https://www.gatsbyjs.org/docs/node-apis/#onCreateNode
[gatsby-mdx]: https://github.com/ChristopherBiscardi/gatsby-mdx
[gatsbyjs/gatsby#3344]: https://github.com/gatsbyjs/gatsby/issues/3344
[gfm]: https://github.github.com/gfm
[gh-52]: https://github.com/arcticicestudio/nord-docs/issues/52
[gh-gatsby-image]: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image
[gh-gatsby-p-sharp]: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp
[gh-gatsby-t-sharp]: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-sharp
[gh-sharp]: https://github.com/lovell/sharp
[mdx-docs-prov]: https://mdxjs.com/getting-started/#mdxprovider
[mdx]: https://mdxjs.com
[npm-bb-poly]: https://www.npmjs.com/package/@babel/polyfill
[npm-cc]: https://www.npmjs.com/package/camelcase
[npm-gat-img]: https://www.npmjs.com/package/gatsby-image
[npm-gat-mdx]: https://www.npmjs.com/package/gatsby-mdx
[npm-gat-p-shp]: https://www.npmjs.com/package/gatsby-plugin-sharp
[npm-gat-t-shp]: https://www.npmjs.com/package/gatsby-transformer-sharp
[npm-glob]: https://www.npmjs.com/package/glob
[npm-mdx-tag]: https://www.npmjs.com/package/@mdx-js/tag
[npm-mdx]: https://www.npmjs.com/package/@mdx-js/mdx
[npm-rh-slug]: https://www.npmjs.com/package/rehype-slug
[npm-rm-br]: https://www.npmjs.com/package/remark-breaks
[npm-rm-gh]: https://www.npmjs.com/package/remark-github
