### ISSUE TITLE
Transition: Nord

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#132]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of Nord to _Nord Docs_. It serves as bridge between the tasks that must be solved for Nord's repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue arcticicestudio/nord#112 for all details.

### Tasks

- [x] Use `target="_blank"` for `Link` component to ensure external URLs are always opened in a new tab/window to keep Nord Docs in focus.
- [x] Implement `SpaceBox` MDX component to allow to adjust layout in MDX documents.
- [x] Create new SVG illustrations for basic documentations.
- [x] Transfer and improve old Nord assets.
- [x] Transfer Nord documentations and polish them.
