### ISSUE TITLE
Transition: Nord JetBrains

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#140]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of [Nord JetBrains][njb] to _Nord Docs_. It serves as bridge between the tasks that must be solved for _Nord JetBrains_ repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue arcticicestudio/nord-jetbrains#48 for all details.

### Tasks

- [x] Transfer and improve old Nord JetBrains assets.
- [x] Update Gatsby Node API implementations to handle images and videos for port project landing pages.
- [x] Implement new content specific illustrations
- [x] Implement new content specific icon components.
- [x] Implement new `Banner` component to highlight important content.
- [x] Make the column ratio of the `FeatureDuo` component configurable to allow to customize the content appearance.
- [x] General refactoring (shared component clean up and duplicate code elimination)
- [x] Transfer Nord JetBrains documentations and polish them.

[njb]: https://github.com/arcticicestudio/nord-jetbrains
