### ISSUE TITLE
Transition: Nord Vim

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#143]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of [Nord Vim][njb] to _Nord Docs_. It serves as bridge between the tasks that must be solved for _Nord Vim_ repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue arcticicestudio/nord-vim#158 for all details.

### Tasks

- [ ] Transfer and improve old Nord Vim assets.
- [ ] Implement new content specific illustrations
- [ ] Implement new content specific icon components.
- [ ] Transfer Nord Vim documentations in polished format.

[nv]: https://github.com/arcticicestudio/nord-vim
