### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#15]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48658871-4707b600-ea49-11e8-8a08-39e1a318c442.png" /></p>

> Must be resolved **before** #16

Integrate [ESLint][], the pluggable and de-facto standard linting utility for JavaScript.

### Configuration Preset

The configuration preset that will be used is [eslint-config-arcticicestudio][gh-eslint-config-arcticicestudio] which implements the [Arctic Ice Studio JavaScript Style][styleguide-javascript]. It it built on top of [eslint-config-arcticicestudio-base][gh-eslint-config-arcticicestudio-base] and includes various rules of the following plugins:

- [eslint-plugin-import][gh-eslint-plugin-import]
- [eslint-plugin-jsx-a11y][gh-eslint-plugin-jsx-a11y]
- [eslint-plugin-react][gh-eslint-plugin-react]

Since the custom preset is still in major version `0` note that the version range should be `>=0.x.x <1.0.0` to avoid NPM's  “SemVer Major Zero Caveat”. When defining package versions with the the carat `^` or tilde `~` range selector it won't affect packages with a major version of `0`. NPM will resolve these packages to their exact version until the major version is greater or equal to `1`.
To avoid this caveat the more detailed version range `>=0.x.x <1.0.0` should be used to resolve all versions greater or equal to `0.x.x` but less than `1.0.0`. This will always use the latest `0.x.x` version and removes the need to increment the version manually on each new release.

To allow to lint all valid Babel code [babel-eslint][gh-babel-eslint] will be included and [specified as main parser][eslint-doc-parser]. Also to make use of the latest experimental Babel features and proposals [eslint-plugin-babel][gh-eslint-plugin-babel] will be added:

- `babel/camelcase` with level `error` - doesn't complain about optional chaining (`let foo = bar?.a_b;`). Note that the [core rule `camelcase`][eslint-rule-camelcase] must be disabled!
- `babel/no-unused-expressions` with level `error` - doesn't fail when using `do` expressions or optional chaining (`a?.b()`). Note that the [core rule `no-unused-expressions`][no-unused-expressions] must be disabled!

See the [documentation of provided rules][gh-eslint-plugin-babel-rules]and required configurations to use them.

The `.eslintrc.js` configuration file will be placed in the project root next to the `.eslintignore` file to define ignore pattern. Initially it will [specify the environments][eslint-docs-config-parser-envs] which define global variables that are predefined:

- `browser` - browser global variables.
- `node` - Node.js global variables and Node.js scoping.

#### Webpack preparations

To prepare for a better developer experience with Webpack (that will be used later on through Gatsby) the [resolvers of the eslint-plugin-import][gh-eslint-plugin-import-resolvers] will be configured for the `src` and `src/components` paths.

#### Disabled rules

Due to compatibility problems and message noise the `no-confusing-arrow` rule will be disabled. It can be re-enabled again when the used preset handles the problem or disables the rule too.

Also to suppress errors in the future with Gatsby the `import/no-extraneous-dependencies` will also be overridden (still error `level`) by adding the `devDependencies` option and add the exception for `./.gatsby/**/*.js`. This allows to use development dependencies in Gatsby configuration files without linting errors since these are necessary and some will be provided by Gatsby itself without being explicitly added to the `package.json`.

### npm script/task

To allow to run the JavaScript linting separately a `lint:js` npm script/task will be added to be included in the main `lint` script flow. To use the great [auto-fixing][eslint-docs-auto-fix] feature another `format:js` script/task will be added.

## Tasks

- [x] Install required packages to `devDependencies`:
  - [babel-eslint][npm-babel-eslint]
  - [eslint][npm-eslint]
  - [eslint-config-arcticicestudio][npm-eslint-config-arcticicestudio]
  - [eslint-plugin-babel][npm-eslint-plugin-babel]
  - [eslint-plugin-import][npm-eslint-plugin-import]
  - [eslint-plugin-jsx-a11y][npm-eslint-plugin-jsx-a11y]
  - [eslint-plugin-react][npm-eslint-plugin-react]
- [x] Implement `.eslintrc.js` configuration file.
  - [x] Specify the `node` and `browser` environments 
  - [x] Use [eslint-config-arcticicestudio][npm-eslint-config-arcticicestudio] preset.
  - [x] [Prepare Webpack](#webpack-preparations) compatibility.
  - [x] Configure [babel-eslint][npm-babel-eslint] as main parser.
  - [x] Disable `no-confusing-arrow` rule
  - [x] Override `import/no-extraneous-dependencies` rule
  - [x] Integrate [eslint-plugin-babel][npm-eslint-plugin-babel]
    - [x] Enable `babel/no-unused-expressions` and `babel/camelcase` rules including the deactivation of their associated core rules.
    - [x] Add `babel` to the array of enabled plugins.
- [x] Implement `.eslintignore` ignore pattern file.
- [x] Implement npm `lint:js` and `format:js` scripts/tasks.
- [x] Lint current code base for the first time and fix possible JavaScript style guide violations.

[eslint]: https://eslint.org
[eslint-doc-parser]: https://eslint.org/docs/user-guide/configuring#specifying-parser
[eslint-docs-auto-fix]: https://eslint.org/docs/user-guide/command-line-interface#fixing-problems
[eslint-docs-config-parser-envs]: https://eslint.org/docs/user-guide/configuring#specifying-environments
[eslint-rule-camelcase]: https://eslint.org/docs/rules/camelcase
[no-unused-expressions]: https://eslint.org/docs/rules/no-unused-expressions
[gh-babel-eslint]: https://github.com/babel/babel-eslint
[gh-eslint-config-arcticicestudio]: https://github.com/arcticicestudio/eslint-config-arcticicestudio
[gh-eslint-config-arcticicestudio-base]: https://github.com/arcticicestudio/eslint-config-arcticicestudio-base
[gh-eslint-plugin-babel]: https://github.com/babel/eslint-plugin-babel
[gh-eslint-plugin-babel-rules]: https://github.com/babel/eslint-plugin-babel#rules
[gh-eslint-plugin-import]: https://github.com/benmosher/eslint-plugin-import
[gh-eslint-plugin-import-resolvers]: https://github.com/benmosher/eslint-plugin-import#resolvers
[gh-eslint-plugin-jsx-a11y]: https://github.com/evcohen/eslint-plugin-jsx-a11y
[gh-eslint-plugin-react]: https://github.com/yannickcr/eslint-plugin-react
[npm-babel-eslint]: https://www.npmjs.com/package/babel-eslint
[npm-eslint]: https://www.npmjs.com/package/eslint
[npm-eslint-config-arcticicestudio]: https://www.npmjs.com/package/eslint-config-arcticicestudio
[npm-eslint-plugin-babel]: https://www.npmjs.com/package/eslint-plugin-babel
[npm-eslint-plugin-import]: https://www.npmjs.com/package/eslint-plugin-import
[npm-eslint-plugin-jsx-a11y]: https://www.npmjs.com/package/eslint-plugin-jsx-a11y
[npm-eslint-plugin-react]: https://www.npmjs.com/package/eslint-plugin-react
[styleguide-javascript]: https://arcticicestudio.github.io/styleguide-javascript
