### ISSUE TITLE
Transition: Nord tmux

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#152]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of [Nord tmux][nt] to _Nord Docs_. It serves as bridge between the tasks that must be solved for _Nord tmux_ repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue [arcticicestudio/nord-tmux](#TODO) for all details.

### Tasks

- [x] Transfer and improve old Nord tmux assets.
- [x] Implement landing and doc page for Nord tmux.
- [x] Transfer Nord tmux documentations in polished format.

[nt]: https://github.com/arcticicestudio/nord-tmux
