### ISSUE TITLE
Transition: Nord Emacs

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#155]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of [Nord Emacs][ne] to _Nord Docs_. It serves as bridge between the tasks that must be solved for _Nord Emacs_ repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue arcticicestudio/nord-emacs#76 for all details.

### Tasks

- [x] Transfer and improve old Nord Emacs assets.
- [x] Implement landing and doc page for Nord Emacs.
- [x] Transfer Nord Emacs documentations in polished format.

[ne]: https://github.com/arcticicestudio/nord-emacs
