### ISSUE TITLE
Transition: Nord Atom Syntax

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#168]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of [Nord Atom Syntax][nas] to _Nord Docs_. It serves as bridge between the tasks that must be solved for _Nord Atom Syntax_ repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue arcticicestudio/nord-atom-syntax#63 for all details.

### Tasks

- [x] Transfer and improve old Nord Atom Syntax assets.
- [x] Implement landing and doc page for Nord Atom Syntax.
- [x] Transfer Nord Atom Syntax documentations in polished format.

[nas]: https://github.com/arcticicestudio/nord-atom-syntax
