### ISSUE TITLE
Transition: Nord Slack

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#175]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of [Nord Slack][s] to _Nord Docs_. It serves as bridge between the tasks that must be solved for _Nord Slack_ repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue arcticicestudio/nord-slack#5 for all details.

### Tasks

- [x] Transfer and improve old Nord Slack assets.
- [x] Implement landing and doc page for Nord Slack.
- [x] Transfer Nord Slack documentations in polished format.

[s]: https://github.com/arcticicestudio/nord-slack
