### ISSUE TITLE
Transition: Nord Xcode

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#182]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="12%"/></p>

> Associated epics: #133

This issue documents the transition of the documentations, assets and visualizations of [Nord Xcode][s] to _Nord Docs_. It serves as bridge between the tasks that must be solved for _Nord Xcode_ repository and the resulting tasks for Nord Docs.

➜ Please see the corresponding issue https://github.com/arcticicestudio/nord-xcode/issues/9 for all details.

### Tasks

- [ ] Transfer and improve old Nord Xcode assets.
- [ ] Implement landing and doc page for Nord Xcode.
- [ ] Transfer Nord Xcode documentations in polished format.

[s]: https://github.com/arcticicestudio/nord-xcode
