### ISSUE TITLE
Gatsby initial configuration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#27]
<p align="center"><img src="https://user-images.githubusercontent.com/74381/34074079-93ac0420-e25c-11e7-9c0a-642986b2aa58.png" width="40%"/></p>

> Related epics: #25, #26

Initially implement the [core configuration of Gatsby][gatsby-docs-config] through the `gatsby-config.js` file that will be placed in the project root. It will define project-wide site metadata that can be used through the GraphQL API and configures all plugins that will be used.

## Site Metadata

All metadata will be, like defined in #26, placed in the corresponding folders for configurations (`src/config`) and data (`src/data`). Initially this will include information stored in the `package.json` file of the project and the [nord][npm-nord] package. There will also be constants for important project root folders to be used in imports later on.

## Gatsby Plugins

This initial implementation will include the following basic plugins:

- [gatsby-plugin-canonical-urls][npm-gp-canonical-urls]
- [gatsby-plugin-catch-links][npm-gp-catch-links]
- [gatsby-plugin-no-sourcemaps][npm-gp-no-sourcemaps]
- [gatsby-plugin-react-helmet][npm-gp-react-helmet]
- [gatsby-source-filesystem][npm-gp-source-filesystem]
- [gatsby-plugin-remove-trailing-slashes][npm-gp-trailing-slashes]
- [gatsby-transformer-yaml][npm-gp-transformer-yaml]

## NPM script

To provide a simple development flow new NPM scripts will be created to start the Gatsby's development mode and build a production bundle. This also includes basic scripts like a clean up to remove possible cache problems and previously created bundles and the currently not available „collected“ scripts to run all scripts of the same type/task. The [npm-run-all][npm-npm-run-all] package will be installed to simplify the scripts and prevent unnecessary long chained commands and OS related problems.

## Tasks

- [x] Install and configure the main [gatsby][npm-gatsby] package and all basic plugins
- [x] Create constants and site metadata configurations
- [x] Implement the new NPM scripts
  - [x] Install the [npm-run-all][npm-npm-run-all] package

[gatsby-docs-config]: https://gatsbyjs.org/docs/gatsby-config
[gatsby-plug-lib]: https://gatsbyjs.org/plugins
[npm-gatsby]: https://www.npmjs.com/package/gatsby
[npm-gp-canonical-urls]: https://www.npmjs.com/package/gatsby-plugin-canonical-urls
[npm-gp-catch-links]: https://www.npmjs.com/package/gatsby-plugin-catch-links
[npm-gp-no-sourcemaps]: https://www.npmjs.com/package/gatsby-plugin-no-sourcemaps
[npm-gp-react-helmet]: https://www.npmjs.com/package/gatsby-plugin-react-helmet
[npm-gp-source-filesystem]: https://www.npmjs.com/package/gatsby-source-filesystem
[npm-gp-trailing-slashes]: https://www.npmjs.com/package/gatsby-plugin-remove-trailing-slashes
[npm-gp-transformer-yaml]: https://www.npmjs.com/package/gatsby-transformer-yaml
[npm-nord]: https://www.npmjs.com/package/nord
[npm-npm-run-all]: https://www.npmjs.com/package/npm-run-all
