### ISSUE TITLE
Babel configuration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#29]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48694124-c3ca9980-ebdb-11e8-9cc3-1379d9ed4a20.png" width="50%"/> <img src="https://user-images.githubusercontent.com/74381/34074079-93ac0420-e25c-11e7-9c0a-642986b2aa58.png" width="25%"/></p> 

> Related epics: #25

Gatsby comes with an already optimized [Babel][] configuration to create SSR “static” websites and apps, but there are also use cases that require to modify and extend this configuration to e.g. add a new Babel [plugin for the latest syntax feature/proposal][babel-docs-plug] support.
Of course Gatsby provides a way through the [Node API][gatsby-docs-api-node] by implementing the [`onCreateBabelConfig`][gatsby-docs-api-node-babel] function.

_Nord Docs_ will make use of the following proposals and plugins:

- [“ES Class Fields & Static Properties”][gh-babel-proposal-cls-fields] through [`@babel/plugin-proposal-class-properties`][babel-docs-plugin-proposal-cls-fields] (**NOTE**: This plugin will be configured with the enabled `loose` option!)
- [“ECMAScript Proposal: export default from”][gh-babel-proposal-exp-def-from] through [`@babel/plugin-proposal-export-default-from`][babel-docs-plugin-proposal-exp-def-from]
- [“Proposal: Nullish Coalescing”][gh-babel-proposal-null-coal] through [`@babel/plugin-proposal-nullish-coalescing-operator`][babel-docs-plugin-proposal-null-coal] (**NOTE**: This plugin will be configured with the disabled `loose` option!)
- [“Proposal: Optional Chaining”][gh-babel-proposal-opt-chain] through [`@babel/plugin-proposal-optional-chaining`][babel-docs-plugin-proposal-opt-chain] (**NOTE**: This plugin will be configured with the disabled `loose` option!)
- [babel-plugin-transform-react-remove-prop-types][gh-babel-plugin-rem-react-props] - Removes unnecessary React `propTypes` from production builds. **NOTE**: This plugin will only be used in `production` mode with enabled `removeImport` option and will ignore the `node_modules` folder through the `ignoreFilenames` option!

The plugins and Babel options will be implemented using [Gatsby's provided actions][gatsby-docs-actions] `setBabelPlugin` and `setBabelOptions`.

## Tasks

- [x] Install required Babel plugin and proposal packages:
  - [@babel/plugin-proposal-class-properties][npm-babel-plugin-prop-cls-fields]
  - [@babel/plugin-proposal-export-default-from][npm-babel-plugin-prop-exp-def-from]
  - [@babel/plugin-proposal-nullish-coalescing-operator][npm-babel-plugin-prop-null-coal]
  - [@babel/plugin-proposal-optional-chaining][npm-babel-plugin-prop-opt-chain]
  - [babel-plugin-transform-react-remove-prop-types][npm-babel-plugin-rem-react-props]
- [x] Configure proposal plugins via the `setBabelPlugin` API function.
- [x] Configure `babel-plugin-transform-react-remove-prop-types` for production build via the `setBabelOptions` API function.

[babel]: https://babeljs.io
[babel-docs-plug]: https://babeljs.io/docs/en/plugins
[babel-docs-plugin-proposal-cls-fields]: https://babeljs.io/docs/en/babel-plugin-proposal-class-properties
[babel-docs-plugin-proposal-exp-def-from]: https://babeljs.io/docs/en/babel-plugin-proposal-export-default-from
[babel-docs-plugin-proposal-null-coal]: https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator
[babel-docs-plugin-proposal-opt-chain]: https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining
[gatsby-docs-actions]: https://www.gatsbyjs.org/docs/actions
[gatsby-docs-api-node]: https://www.gatsbyjs.org/docs/node-apis
[gatsby-docs-api-node-babel]: https://www.gatsbyjs.org/docs/node-apis/#onCreateBabelConfig
[gh-babel-proposal-cls-fields]: https://github.com/tc39/proposal-class-fields
[gh-babel-proposal-exp-def-from]: https://github.com/tc39/proposal-export-default-from
[gh-babel-proposal-null-coal]: https://github.com/tc39/proposal-nullish-coalescing
[gh-babel-proposal-opt-chain]: https://github.com/tc39/proposal-optional-chaining
[gh-babel-plugin-rem-react-props]: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types
[npm-babel-plugin-prop-cls-fields]: https://www.npmjs.com/package/@babel/plugin-proposal-class-properties
[npm-babel-plugin-prop-exp-def-from]: https://www.npmjs.com/package/@babel/plugin-proposal-export-default-from
[npm-babel-plugin-prop-null-coal]: https://www.npmjs.com/package/@babel/plugin-proposal-nullish-coalescing-operator
[npm-babel-plugin-prop-opt-chain]: https://www.npmjs.com/package/@babel/plugin-proposal-optional-chaining
[npm-babel-plugin-rem-react-props]: https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types
