### ISSUE TITLE
Webpack configuration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#31]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48711809-761a5500-ec0c-11e8-8ba7-dc4acbd5d64c.png" width="70%"/> <img src="https://user-images.githubusercontent.com/74381/34074079-93ac0420-e25c-11e7-9c0a-642986b2aa58.png" width="20%"/></p> 

> Related epics: #25

This story is almost the same like the modified Babel configuration implemented in #29, but for the [Webpack][] configuration instead. It will be used to

- configure the plugin [webpack-bundle-analyzer][gh-webpack-bundle-analyzer]
- configure the plugin [git-revision-webpack-plugin][gh-git-revision-webpack-plugin]
- configure the plugin [webpack.DefinePlugin][webpack-docs-define-plug]
- configure [resolve aliases][webpack-docs-resolve-alias] (see #26 for details about the structure concept)

Gatsby also supports this by providing the [`onCreateWebpackConfig`][gatsby-docs-api-node-webpack] function through the [Node API][gatsby-docs-api-node].

## Tasks

- [x] Install required Webpack plugin packages:
  - [webpack-bundle-analyzer][npm-webpack-bundle-analyzer]
  - [git-revision-webpack-plugin][npm-git-revision-webpack-plugin]
- [x] Configure resolve aliases for
  - `src/assets`
  - `src/atoms`
  - `src/config`
  - `src/containers`
  - `src/data`
  - `src/layouts`
  - `src/molecules`
  - `src/organisms`
  - `src/pages`
  - `src/stores`
  - `src/styles`
  - `src/templates`
  - `src/utils`
- [x] Configure `git-revision-webpack-plugin` to provide the version, commit hash and branch as environment variables through through the `webpack.DefinePlugin`.
- [x] Configure `webpack-bundle-analyzer` to generate a "static" report with a JSON stats file stored in a newly created `build` directory within the project root.

[gatsby-docs-api-node]: https://www.gatsbyjs.org/docs/node-apis
[gatsby-docs-api-node-webpack]: https://www.gatsbyjs.org/docs/node-apis/#onCreateWebpackConfig
[gh-git-revision-webpack-plugin]: https://github.com/pirelenito/git-revision-webpack-plugin
[gh-webpack-bundle-analyzer]: https://github.com/webpack-contrib/webpack-bundle-analyzer
[npm-git-revision-webpack-plugin]: https://www.npmjs.com/package/git-revision-webpack-plugin
[npm-webpack-bundle-analyzer]: https://www.npmjs.com/package/webpack-bundle-analyzer
[webpack]: https://webpack.js.org
[webpack-docs-define-plug]: https://webpack.js.org/plugins/define-plugin
[webpack-docs-resolve-alias]: https://webpack.js.org/configuration/resolve/#resolve-alias
