### ISSUE TITLE
Basic testing setup

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#39]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48822935-24ceaa80-ed5f-11e8-8328-eec53dfc68f9.png" width="30%"/></p>

> Related epics: #38

To start writing tests the basic testing environment must be set up. As also mentioned in #38, _Nord Docs_ requires some special changes when it comes to the testing setup because of Gatsby. Apart from that the setup is the same like in most projects and is also documented in the official [Jest docs][jest].

The scope of this issue is to get started to write _unit tests_. Of course, Gatsby provides a [extensive documentation and great guides for this setup][gatsby-docs-testing] which will be implemented for _Nord Docs_.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48837384-7ab64900-ed85-11e8-829c-3fd6efe86c60.png" width="50%"/></p>

## Jest

The first step is to get [Jest][npm-jest] up and running which is quite easy since it works out-of-the-box™ after installing the main package [jest][npm-jest].
This step is documented in the sections [“Setting up your environment”][gatsby-docs-testing-setup-env] of the Gatsby guide and the Jest docs about [how to get started][jest-docs-start].

The main configuration file `jest.config.js` will be placed in the project root and initially contains the following options:

- `coverageDirectory` - The path to the directory where all coverage reports will be placed. It'll be set to the main `build` directory within the `reports` sub-directory.
- `collectCoverageFrom` - To ensure only relevant files are included in the coverage stats this array will set paths to find sources to measure the coverage from.
- `globals` - This will include the `__PATH_PREFIX__` variable which is usually set by Gatsby, and which some components need.
- `moduleNameMapper` - A map from regular expressions to module names that allow to stub out resources, like images or styles with a single module while also allows to set up resolve aliases which will reflect the same setup like the ones configured for Webpack in #31.
- `modulePaths` - This will include paths to additional locations to search when resolving modules which is useful to define test specific utils which can then be imported like a aliased module.
- `setupFiles` - This also includes setup scripts that'll be run to configure and set up tests (executed before `setupTestFrameworkScriptFile`) and will initial include a shim mock for the `___loader` function used by Gatsby.
- `setupTestFrameworkScriptFile` - The setup file that'll be run to configure or set up the testing framework before each test. It'll import and run the `cleanup` function of `react-testing-library` and `jest-dom`'s custom matchers to extend the `expect` global.
- `testPathIgnorePatterns` - Paths for files that'll be ignored when matching test files have been found.
- `transform` - Contains regex matcher for files that will be transpiled with Babel first before run them with Jest. See the [“Use Jest with Babel”](#use-jest-with-babel) section below for details.
- `transformIgnorePatterns` - This is required since Gastby includes un-transpiled ES6 code and by default Jest doesn’t try to transform code inside `node_modules`, therefore the `gatsby-browser-entry.js` isn't transpiled before running Jest so the `gatsby` module must be excluded.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48694124-c3ca9980-ebdb-11e8-9cc3-1379d9ed4a20.png" width="40%"/></p>

## Use Jest with Babel

To write tests using the latest ECMAScript syntax and proposals, [Babel][] must be in place and set up to transpile the sources before passing them to Jest to run them.
This step is documented in the sections [“Creating a configuration file for Jest”][gatsby-docs-testing-jest-conf] of the Gatsby guide about the preprocess file and the Jest docs about [using babel][jest-docs-babel].

The main Babel configuration file `babel-config.js` will be placed in the base `test` folder within the project root. It'll initially use the [babel-preset-gatsby][npm-babel-preset-gatsby] preset package which includes all necessary Babel plugins to write tests for Gatsby based projects. This includes all plugins mentioned in the [Jest Babel setup guide][jest-docs-babel] and additionally adds useful syntax proposal plugins that are also used in the project sources like e.g. [babel-plugin-proposal-class-properties][babel-docs-plug-prop-cls-props] and [babel-plugin-proposal-optional-chaining][babel-docs-plug-opt-chain].
The the custom transformer will be exported using [babel-jest's `createTransformer` function][jest-docs-react-transformer] which takes the created Babel config object as parameter.

react-testing-library provides a function to get elements by an test ID using the `data-testid` property (attribute) that can be added to any React component's JSX so it can be easily queried in tests. **Note that this should only be done [when there is no other way which is documented in the guiding principles][gh-rtl-gprinc]!**
Since this property is **only** relevant for test purposes it should and will be removed for production builds using the [babel-plugin-react-remove-properties][npm-babel-plugin-react-remove-properties] package that'll be included in Gatsby's Babel configuration and loaded when in production mode.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48944792-74ac9d80-ef28-11e8-8976-6fd146501d45.png" width="10%"/> <img src="https://user-images.githubusercontent.com/7836623/48837576-07610700-ed86-11e8-9730-ebcb22b167d1.png" width="20%"/></p>

## react-testing-library and jest-dom

Like documented in #38, _Nord Docs_ will use the awesome [react-testing-library][gh-rtl] by Kent C. Dodds to render React components and test them with a bunch of useful DOM utils. _Nord Docs_ testing principle is based on the concept of the author to not test implementation details for UIs but see your app/website only from the sight of the user.

The [setup documentation][gh-rtl-setup] provides instruction for best practices on how to configure the library for a optimal and easy developer workflow. This includes a global configuration that'll be added and loaded via Jest's `setupTestFrameworkScriptFile` option and will be placed within the `test` base directory named `setup.js`.
Initially it'll import the `react-testing-library/cleanup-after-each` script which will automatially execute `afterEach(cleanup)` for each test which prevents unnecessary boilerplate per test file and possible problems when the function is not called accidentally. It'll also import `jest-dom/extend-expect` to automatically extend the `expect` global with [jest-dom's custom matchers][jest-dom-matcher].

<p align="center"><img src="https://user-images.githubusercontent.com/74381/34074079-93ac0420-e25c-11e7-9c0a-642986b2aa58.png" width="30%"/></p>

## Shims

Like documented in [Gatsby's official testing setup guide][gatsby-docs-testing-setup-env] there are some configurations that are specific to Gatsby projects. One is the global `___loader` function used by Gatsby which must be mocked using Jest's `fn()` mocking function. The `___loader.js` file will be created in a folder called `__shims__` within the base `test` directory.

## Mocks

With Webpack, there are [many loaders available to load any kind of file type][webpack-docs-loaders], e.g. CSS or Sass/Less for styles and images/videos of many types. Jest doesn't know how to handle these when these are imported within source files that are normally processed by Webpack so it'll throw errors during the import.
A [Jest mock][jest-docs-manmock] is a dummy module that is used instead of the real module inside tests. It is good when there are something that you can’t or don’t want to test. Almost everything can be mocked and the examples are assets rather than code. For stylesheets, there is a package called [identity-obj-proxy][npm-identity-obj-proxy] which is also already configured for this project. For all other assets a manual mock will be created called `file.js` that'll be created in a new `__mocks__` folder within the base `test` directory.
To configure Jest to use these mocks the matching regex for the files will be added to the `moduleNameMapper` option.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48658871-4707b600-ea49-11e8-8a08-39e1a318c442.png" /></p>

## ESLint

Since Jest makes use of the globally provided functions, ESLint's environment must be configured to know that Jest is used in the project. This can easily be done by adding the `jest: true` property to the `env` option in the `.eslintrc.js` config file.

## NPM scripts

To allow to run all tests with various options there will be some new NPM scripts:

- `test` - Run all tests with Jest.
- `test:cov` - Run all tests with [coverage reports][jest-docs-cli-coverage].
- `test:watch` - Run all tests in Jest's [_watch mode_][jest-docs-cli-watch].

## Tasks

- [x] Install required dependencies:
  - (dev) [@babel/core][npm-@babel/core]
  - (dev) [babel-jest][npm-babel-jest]
  - (dev) [babel-plugin-react-remove-properties][npm-babel-plugin-react-remove-properties]
  - (dev) [babel-preset-gatsby][npm-babel-preset-gatsby]
  - (dev) [identity-obj-proxy][npm-identity-obj-proxy]
  - (dev) [jest][npm-jest]
  - (dev) [jest-dom][npm-jest-dom]
  - (dev) [react-testing-library][npm-react-testing-library]
- [x] Implement the [Jest main configuration](#jest) file (`jest.config.js`)
- [x] Implement [Jest's Babel configuration](#use-jest-with-babel) file (`test/babel-config.js`)
- [x] Configure the [Babel plugin to remove properties from production builds](#use-jest-with-babel) in Gatsby's Webpack configuration
- [x] Implement [Jest's test framework setup configuration](#react-testing-library-and-jest-dom) file (`test/setup.js`) for _react_testing-library_ and _jest-dom_
- [x] Implement Gatsby specific [mocks](#mocks) and [shims](#shims)
- [x] [Configure ESLint](#eslint) for Jest's global functions with the `jest` environment
- [x] Implement [NPM scripts for multiple test tasks](#npm-scripts)
- [x] Implement initial snapshot tests for existing components (they actually only render a React `<Fragment>`)

[babel]: https://babeljs.io
[babel-docs-plug-opt-chain]: https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining
[babel-docs-plug-prop-cls-props]: https://babeljs.io/docs/en/babel-plugin-proposal-class-properties
[gatsby-docs-testing]: https://www.gatsbyjs.org/docs/testing
[gatsby-docs-testing-setup-env]: https://www.gatsbyjs.org/docs/unit-testing/#setting-up-your-environment
[gatsby-docs-testing-jest-conf]: https://www.gatsbyjs.org/docs/unit-testing/#2-creating-a-configuration-file-for-jest
[gh-babel-plug-rem-props]: https://github.com/oliviertassinari/babel-plugin-react-remove-properties
[gh-rtl]: https://github.com/kentcdodds/react-testing-library
[gh-rtl-setup]: https://github.com/kentcdodds/react-testing-library#setup
[gh-rtl-gprinc]: https://github.com/kentcdodds/react-testing-library#guiding-principles
[jest]: https://jestjs.io
[jest-docs-babel]: https://jestjs.io/docs/en/getting-started#using-babel
[jest-docs-start]: https://jestjs.io/docs/en/getting-started
[jest-docs-manmock]: https://jestjs.io/docs/en/manual-mocks
[jest-docs-cli-watch]: https://jestjs.io/docs/en/cli#watch
[jest-docs-cli-coverage]: https://jestjs.io/docs/en/cli#coverage
[jest-docs-react-transformer]: https://jestjs.io/docs/en/tutorial-react#custom-transformers
[npm-@babel/core]: https://www.npmjs.com/package/@babel/core
[npm-babel-jest]: https://www.npmjs.com/package/babel-jest
[npm-babel-plugin-react-remove-properties]: https://www.npmjs.com/package/babel-plugin-react-remove-properties
[npm-babel-preset-gatsby]: https://www.npmjs.com/package/babel-preset-gatsby
[npm-identity-obj-proxy]: https://www.npmjs.com/package/identity-obj-proxy
[npm-jest]: https://www.npmjs.com/package/jest
[npm-jest-dom]: https://www.npmjs.com/package/jest-dom
[npm-react-testing-library]: https://www.npmjs.com/package/react-testing-library
[jest-dom-matcher]: https://github.com/gnapse/jest-dom#custom-matchers
[webpack-docs-loaders]: https://webpack.js.org/loaders
