### ISSUE TITLE
Continuous Integration & Testing

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#44]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48966346-26eb7000-efd0-11e8-818b-80035dd538ca.png" width="30%"/></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48966407-4636cd00-efd1-11e8-9724-fc26fc97851b.png" width="8%"/> <img src="https://user-images.githubusercontent.com/7836623/48966652-0faf8100-efd6-11e8-865e-9a07bbc847c6.png" width="8%"/> <img src="https://user-images.githubusercontent.com/7836623/48966681-cca1dd80-efd6-11e8-953e-8734a9d4d3f7.png" width="8%"/></p>

> Related epics: #43

This issue documents the implementation and configuration of the workflow for the [continuous integration & testing concept][gh-43] with [Circle CI][cci], [Travis CI][tci] and [Codecov][cc].

## Workflow

**NOTE:**: There are small differences between the setup for Circle CI and Travis CI so all steps are marked which provider the step will be applied to!

1. ![][icon-cci]
   **Checkout of the source code** - Clone the GitHub repository to the CI container as working directory.
2. ![][icon-cci]![][icon-tci]
   **Print build and environment information** - Prints details like the branch name, commit hash and container data. See the provider specific documentations for [Circle CI][cci-docs-env-vars] and [Travis CI][tci-docs-env-vars].
3. ![][icon-cci]![][icon-tci]
   **Restore the dependency cache (`node_modules`)** - Restore the `node_modules` folder based on the checksum of the `package-lock.json` file and an version prefix which allows to simply invalidate the cache. See the provider specific documentations for [Circle CI][cci-docs-cache] and [Travis CI][tci-docs-cache].
4. ![][icon-cci]![][icon-tci]
   **Install the dependencies** - Run NPM `install` command to install all dependencies.
5. ![][icon-cci]![][icon-tci]
    **Install the Codecov CLI globally** - To upload the coverage reports (generated in later steps) [Codecov provides a NPM package][npm-codecov-node] as CLI which can be installed globally and called in CI build steps.
6. ![][icon-cci]![][icon-tci]
   **Run all configured linters** - Run all installed and configured linters using the `lint` NPM script.
7. ![][icon-cci]![][icon-tci]
   **Run all tests** - Run all unit, integration and end-to-end tests and generate the coverage report using the `test` NPM script.
8. ![][icon-cci]![][icon-tci]
   **Build a production bundle** - Generate a production build with Gatsby using the `build` NPM script.
9. ![][icon-cci]![][icon-tci]
   **Save the dependency cache (`node_modules`)** - Save the `node_modules` folder again to the cache based on the checksum of the `package-lock.json` file and the version prefix which allows to simply invalidate the cache. See the provider specific documentations for [Circle CI][cci-docs-cache] and [Travis CI][tci-docs-cache].
10. ![][icon-cci]![][icon-tci]
    **Upload generated coverage reports to Codecov** - [Codecov provides a NPM package][npm-codecov-node] which detects the CI it runs on and automatically uploads the reports.
11. ![][icon-cci]![][icon-tci]
    **Store all generated artifacts** - This includes the whole production bundle stored in the created `public` folder, the coverage and webpack bundle reports in the `build/reports` folder and the `node_modules_` dependency folder to allow to reproduce the build locally with the exact same resolved dependencies.

## GitHub Integration Configuration

Like also documented in #43 the integration of the CI and coverage services with GitHub requires to [configure the rules for protected branches][ghh-protec-br]. See the design concept for more details.

## Tasks

- [ ] Implement the `.circleci/config.yml` configuration file for Circle CI
- [ ] Implement the `.travis.yml` configuration file for Travis CI
- [ ] Configure the integration with GitHub

[cc]: https://codecov.io
[cci]: https://circleci.com
[cci-docs-cache]: https://circleci.com/docs/2.0/caching
[cci-docs-env-vars]: https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
[gh-43]: https://github.com/arcticicestudio/nord-docs/issues/43
[ghh-protec-br]: https://help.github.com/articles/configuring-protected-branches
[icon-cci]: https://user-images.githubusercontent.com/7836623/48967027-26a4a200-efdb-11e8-88b4-5e7e5df8b0bc.png
[icon-tci]: https://user-images.githubusercontent.com/7836623/48967035-476cf780-efdb-11e8-8b80-5af4c2d21f3b.png
[npm-codecov-node]: https://github.com/codecov/codecov-node
[tci]: https://travis-ci.org
[tci-docs-cache]: https://docs.travis-ci.com/user/caching
[tci-docs-env-vars]: https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
