### ISSUE TITLE
Base Style & Theme Setup

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#53]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/49328407-a4832300-f570-11e8-8613-21c78267b558.png" width="20%" /></p>

> Associated epic: #51

To start implementing components the basic styles and must be set up. As documented in #51, _Nord Docs_ will uses the CSS-in-JS library [styled-components][]. To use uniform global theme definitions and to simplify CSS styling, the [styled-theming][gh-styled-theming] and [polished][] libraries will be integrated next to some useful and required specific Babel & Gatsby plugins.

## Normalization Of Default Browser Styles

The [modern-normalize][gh-modern-normalize] is a great project that normalizes the browsers default styles for a consistent appearance across different modern browsers. For the best usage with _styled-components_ the [npm-styled-modern-normalize][npm-styled-modern-normalize] project will be used. It exports the styles via the `css` API and will be added to the created global styles component mentioned above.

## CSS Tools

To simplify the CSS styling, the [polished][] package will be used that provides a lightweight toolset for writing styles in JavaScript (CSS-in-JS).

## CSS Base Styles

To define global CSS styles a `baseline` file will be implemented using _styled-components_ `css` API. It extends _modern-normalize_ and includes, next to the browser normalization, styles of the available global themes like documented in the sections below.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48661206-c0fe6600-ea6e-11e8-8142-4c65c82b9927.png" /></p>

## Global Styles

To inject global styles, _styled-components_ v4 [`createglobalstyle`][stc-docs-api-cgs] API will be used to create a `<GlobalStyle>` component that can then be used to inject various styles globally.

## Global Themes

To [provide the global theme][stc-docs-theming], the [`ThemeProvider`][stc-docs-api-thp] component will be added to the _Nord Docs_ [`Root` core container component][gh-36]. The global theme, placed in `src/styles/themes` will then be passed to the provider.

### Simplified Theme Usage

To simplify the usage of _styled-theming's_ [`theme()`][gh-stth-api-th] and `theme.variants()` API functions, two utility functions will be implemented:

- `themeMode(modeStyles : object)` — Shorthand function for the `theme` API to define styles based on the global theme mode(s).
- `themedModeVariant(modeStyles : object, variantPropName : string)` — Shorthand function for the `theme.variants` API to define variant styles based on the global theme mode(s).

### Available Themes

Initially _Nord Docs_ will be build with the “bright snow flurry” and “dark night frost” _theme modes_. The names will be implemented as constants with values `BRIGHT_SNOW_FLURRY` and `DARK_NIGHT_FROST` to be used with the utility functions mentioned above to define the styles of a component for each available global theme.

## Plugins

[_styled-components_ great Babel plugin][stc-docs-tool-babel] adds support for server-side rendering, minification of styles, and a nicer debugging experience. It will be integrated via the [corresponding Gatsby's plugin][npm-gatsby-plugin-styled-components].

## Nord Colors

Since the main [JavaScript implementation of Nord][gh-nord-36] is currently not completed and released yet, the colors and palettes will be provided "manually" via the `nord` and `palettes` modules. As soon as the implementation has been done they will be replaced through imports from the official package.

## Tasks

- [ ] Install all (dev) dependencies:
  - [styled-components][npm-styled-components]
  - [styled-theming][npm-styled-theming]
  - [polished][npm-polished]
  - [babel-plugin-styled-components][npm-babel-plugin-styled-components]
  - [gatsby-plugin-styled-components][npm-gatsby-plugin-styled-components]
  - [styled-modern-normalize][npm-styled-modern-normalize]
- [ ] Implement CSS base style into a `baseline` file with _styled-components_ `css` API.
- [ ] Create the `<GlobalStyle>` component to inject `styled-modern-normalize` and CSS `baseline` styles.
- [ ] Add `ThemeProvider` component to `Root` core container.
- [ ] Implement the `themeMode` and `themeModeVariants` theme utility functions.
- [ ] Create constants for the `BRIGHT_SNOW_FLURRY` and `DARK_NIGHT_FROST` _theme modes_.
- [ ] Setup _styled-components_ Babel plugin via the corresponding Gatsby plugin.
- [ ] Implement temporary `nord` and `palettes` modules.

[gh-36]: https://github.com/arcticicestudio/nord-docs/issues/36
[gh-modern-normalize]: https://github.com/sindresorhus/modern-normalize
[gh-nord-36]: https://github.com/arcticicestudio/nord/issues/36
[gh-stth-api-th]: https://github.com/styled-components/styled-theming#themename-values
[gh-styled-theming]: https://github.com/styled-components/styled-theming
[polished]: https://polished.js.org
[npm-babel-plugin-styled-components]: https://www.npmjs.com/package/babel-plugin-styled-components
[npm-gatsby-plugin-styled-components]: https://www.npmjs.com/package/gatsby-plugin-styled-components
[npm-polished]: https://www.npmjs.com/package/polished
[npm-styled-components]: https://www.npmjs.com/package/styled-components
[npm-styled-modern-normalize]: https://www.npmjs.com/package/styled-modern-normalize
[npm-styled-theming]: https://www.npmjs.com/package/styled-components
[stc-docs]: https://www.styled-components.com/docs
[stc-docs-api]: https://www.styled-components.com/docs/api
[stc-docs-api-cgs]: https://www.styled-components.com/docs/api#createglobalstyle
[stc-docs-api-thp]: https://www.styled-components.com/docs/api#themeprovider
[stc-docs-theming]: https://www.styled-components.com/docs/advanced#theming
[stc-docs-tool-babel]: https://www.styled-components.com/docs/tooling#babel-plugin
[styled-components]: https://www.styled-components.com
