### ISSUE TITLE
Theme Mode Context

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#57]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/49328407-a4832300-f570-11e8-8613-21c78267b558.png" width="20%" /></p>

> Associated epic: #51

This issue handles the implementation of the [`React.Context` provider and consumer][react-docs-context] for the global theme modes. It will provide the name of the currently active theme and a function to toggle the active theme.

## Context Provider & Consumer

Both the context consumer and provider components will be implemented in the [`Root` core container component][gh-36]. The consumer will be exported which can then be imported in any component to consume the provided values.

The `Root` component will be changed from a SFC to a class component to store the currently active state and handle the theme mode toggle logic through a function. It will also migrate the currently used simple [styled-component theme][stc-docs-theming] (provided through the `<ThemeProvider` component) to the [styled-theming theme][gh-styled-theming] that provides the initially implemented theme (#53).

## Session Storage

To persist the current active theme mode when changing the route (which unmounts the `Root` component and therefore resets the state), the value will be written to the browser's [session storage][mdn-ss]. The storage type has been preferred over the [local storage][mdn-ls] since this would persist the active theme mode even when the user closes the tab, but the desired behavior is to optimize the site for the “bright snow flurry” aura theme mode.

To simplify the read- and write handling as well as prevent possible errors due to wrong storage keys, two utility functions will be implemented: `readSessionCache(key : string)` and `writeSessionCache(key : string, value : any)`.

## Tasks

- [x] Implement `readSessionCache` and `writeSessionCache` utility functions.
- [x] Implement the theme context provider & consumer components.
- [x] Rewrite the `Root` core container as class-based component.
  - Store the currently active theme mode in `state`.
  - Hydrate `state` with the theme mode stored in the _session storage_ on component instantiation.
  - Implement the function to toggle the theme mode.
  - Compose the _styled-theming_ theme object with the theme mode value.
  - Ensure to pass the `theme` to the `GlobalStyle` component for global theme styles.

[gh-36]: https://github.com/arcticicestudio/nord-docs/issues/36
[gh-styled-theming]: https://github.com/styled-components/styled-theming
[mdn-ls]: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
[mdn-ss]: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage
[react-docs-context]: https://reactjs.org/docs/context.html
[stc-docs-theming]: https://www.styled-components.com/docs/advanced#theming
