### ISSUE TITLE
Core Organism Component: Header

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#64]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="15%"/></p>

> Associated epic: #63, #2, #69
> Depends on: #66, #70, #72

This issue documents the core organism component `Header` which is an essential part of _Nord Docs_. It'll provide the main site navigation and a user action component to [toggle between the global theme modes][gh-57].

## Layout

The header will use a CSS _flexbox_ layout consisting of two container components with the maximum of flexible space between both. The containers will contain the branding component and the navigation like documented in the sections below.

### Navigation

To allows users to simply navigate around the site, the component will provide the quickly accessible navigation. The navigation will be placed in the right-sided container.

As of now the following items are planned:

- “Ports” — links to `/ports`, the landing page for all Nord port projects.
- “Docs” — links to `/docs`, the landing page for Nord's documentation.
- “Blog” — links to `/blog`, the landing page for Nord's blog.
- “Community” — links to `/community`, the landing page of the Nord community channels.

### Branding

To represent Nord's branding, the left-sided container will contain the Nord logo with a label. It'll link to _Nord Docs_ landing page to allow quick access to the root (`/`) page.

## Theme Mode Switcher

The user action component mentioned in the introduction paragraph above will allows to toggle between the available global theme modes. Both modes will be represented through icons where a sun is used for “bright snow flurry” and a moon for “dark night frost” mode. They'll be implemented using the awesome [React Pose][rp] project to animate the switching. The icons will “fly out and in” within the bounds of the component that'll take the form of a button.

Like documented in the [Iconography design concept][gh-74], the awesome [Eva Icons][eva-icons] project will be used where the “moon” and “sun” icons will represent the both available theme modes.

## Responsive Design

For reduced width views (responsive design) the header will adjust several styles and composed components.

### Slide Menu

The main navigation link list will be hidden and replaced by a user action element (button) that toggles an animated slide down menu containing the navigation links. The drop down will start right below the header and take up the available height and width to cover the full screen. As soon as the animation starts all scroll events will be removed from the underlying content (body) using the [body-scroll-lock][gh-bsl] project. This prevents users from scrolling the content below the menu when the menu itself overflows the Y-axis and shows a scroll bar.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/49829535-fc026980-fd8e-11e8-9cba-d5d6e8149c10.png" width="25%"/></p>

## Behavior

To allow quick access while also being inconspicuous, the component will be _sticky_ at the top of the site, but will collapse as soon as the user scrolls down. It'll only switch into expanded mode when at top of the site.
In expanded mode, the height of the header will be larger and the label of the logo will be visible. As soon as switching into collapsed mode the height will decrease and the logo label will fade out with a smooth transition animation.

To achieve the resizing animation based on the scroll position the [subscribe-ui-event][gh-sue] project will be used to listen to scroll events. It provides throttling by default, only calls `document.body.scrollTop` and `window.innerWidth` once and uses `requestAnimationFrame` for the best performance.

## Tasks

- [x] Install required dependencies:
  - [body-scroll-lock][npm-bsl]
  - [react-pose][npm-rp]
  - [subscribe-ui-event][npm-sue]
  - [eslint-import-resolver-jest][npm-esl-irj]
- [x] Implement vector icon and logo components for the theme mode switcher.
- [x] Adjust and improve CSS media query breakpoints.
- [x] Install [eslint-import-resolver-jest][gh-esl-irj] plugin for test util function path resolving.
- [x] Implement test utility function to render components with the global theme and modes.
- [x] Implement core container component to handle maximum content width.
- [x] Implement navigation link data with route mappings.
- [x] Implement _modular scale_ utility function (see #2).
- [x] Implement utility function to handle the `z-index` order of all components.
- [x] Improve [core atom HTML element `A`][gh-70] to handle `innerRef` forwarding.
- [x] Improve motion speed styles for new animations.
- [x] Implement required _local_ styled atom components for `Header`.
- [x] Implement the main `Header` component.

[eva-icons]: https://akveo.github.io/eva-icons
[gh-57]: https://github.com/arcticicestudio/nord-docs/issues/57
[gh-70]: https://github.com/arcticicestudio/nord-docs/issues/70
[gh-74]: https://github.com/arcticicestudio/nord-docs/issues/74
[gh-bsl]:https://github.com/willmcpo/body-scroll-lock
[gh-esl-irj]: https://github.com/JoinColony/eslint-import-resolver-jest
[gh-sue]: https://github.com/yahoo/subscribe-ui-event
[npm-bsl]: https://www.npmjs.com/package/body-scroll-lock
[npm-esl-irj]: https://www.npmjs.com/package/eslint-import-resolver-jest
[npm-sue]: https://www.npmjs.com/package/subscribe-ui-event
[npm-rp]: https://www.npmjs.com/package/react-pose
[rp]: https://popmotion.io/pose
