### ISSUE TITLE
Jest utilities for Styled Components 

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#76]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48661206-c0fe6600-ea6e-11e8-8142-4c65c82b9927.png" /></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48837384-7ab64900-ed85-11e8-829c-3fd6efe86c60.png" width="40%"/></p>

> Associated epics: #38
> Associated issues: #39

This issue documents the integration of the [jest-styled-components][gh-jsc], a set of utilities for testing [Styled Components][styled-components] with [Jest][] that improves the snapshot testing experience and provides a brand new matcher to make expectations on the style rules.
This is the officially [recommended library styled-components for Jest integration][st-docs-tooling-jest].

Instead of storing the generated class names in snapshots it allows to track the actual CSS rules and attributes for **better comparison what changed** and **if the change is even really related to the affected component**.

```js
const Button = styled.button`
  color: red;
`
```

```js
exports[`snapshot`] = `
<button
  className="sc-bdVaJa rOCEJ"
/>
`;
```

**Before**

```diff
- Snapshot
+ Received

 <button
-  className="sc-bdVaJa rOCEJ"
+  className="sc-bdVaJa hUzqNt"
 />
```

**After**

```diff
- Snapshot
+ Received

+.c0 {
+  color: green;
+}
+
 <button
-  className="sc-bdVaJa rOCEJ"
+  className="c0"
 />
```

## Configuration

To enable this feature the package can simply being imported in the setup file defined in Jest's `setupTestFrameworkScriptFile` field implemented in #39.

```js
import "jest-styled-components";
```

## Custom Style Matcher

The [custom `toHaveStyleRule` matcher][gh-jsc-matcher] is useful to test if a given rule is applied to a component. It will be added to the extended global `except` object when the main package file is being imported.

## Tasks

- [x] Install the required packages:
  - [jest-styled-components][npm-jsc]
- [x] Import the main package file into the defined Jest test framework script file (`test/setup.js`).
- [x] Update existing and implement missing tests for style-only components.

[gh-jsc]: https://github.com/styled-components/jest-styled-components
[gh-jsc-matcher]: https://github.com/styled-components/jest-styled-components#tohavestylerule
[jest]: https://jestjs.io
[npm-jsc]: https://www.npmjs.com/package/jest-styled-components
[st-docs-tooling-jest]: https://www.styled-components.com/docs/tooling#jest-integration
[styled-components]: https://www.styled-components.com
