### ISSUE TITLE
Empty State Component

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#78]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="20%"/></p>

> Associated epics: #63, #68

This issue documents the implementation of the molecule component to represent an [empty state][md-es].

## Structure

The component will consists of three parts: an vector illustration, the headline and the corresponding subline.

### Vector Illustration

The illustration will be the main element. The component will provide multiple illustrations that can be selected through a prop.

### Headline

The headline will inform the user about the purpose of the illustration and the reason why it is currently shown.

### Subline

The subline includes information and helpful instructions in addition to the headline.

## Base Sectioning Component

The empty state component will be placed within a base HTML component that represents a [`<section>`][mdn-web-el-sec] with multiple base style variants.

## Initial Usage

The new empty state component will be initially used by implementing the base page components for missing [header navigation links][gh-64].

## Tasks

- [x] Implement base styled sectioning component.
- [x] Implement vector illustrations and styled components.
- [x] Implement the `EmptyState` component.
- [x] Implement missing base page components for [header navigation links][gh-64].

[gh-64]: https://github.com/arcticicestudio/nord-docs/issues/64
[md-es]: https://material.io/design/communication/empty-states.html
[mdn-web-el-sec]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
