### ISSUE TITLE
404 Page Components

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#84]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48676311-39475300-eb65-11e8-9654-16c24c1c9a94.png" width="20%"/></p>

> Associated epics: #63

This issue documents the implementation of [404][wiki-404] page and illustration component to handle requested but non-existing routes and resources.

## Structure

The component will consist of three parts: an vector illustration, the headline and the corresponding subline.

### Vector Illustration

The illustration will be the main element of the page component. It will present the exception/error case with a friendly visualization.

### Text Content

The headline and subline will inform the user about the purpose of the illustration and the reason why it is currently shown and can include helpful instructions on how to continue.

## Tasks

- [ ] Implement the vector illustration and styled components.
- [ ] Implement the `ErrorState404` component.
- [ ] Implement the 404 page component.

[wiki-404]: https://en.wikipedia.org/wiki/HTTP_404
