### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#87]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/50167256-14bbd380-02e9-11e9-8aca-a31baf745cd8.png" width="20%"/></p>

> Associated epic: #86

This issue documents the implementation of [Google Analytics][ga-mark] like documented in the [“Analytics & Statistics” design concept][gh-86].

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/50167593-c824c800-02e9-11e9-9b70-84b6fc40c05f.png " width="20%"/></p>

The main tool to collect and analyze data will be [Google Analytics][ga-mark]. It is a stable and proven service with a lot of useful configurable features and a reliable persistence.

_Nord Docs_ will use the latest and recommended [gtag.js][gdev-ga-gtag] library that optionally allows, next to Google Analytics itself, the integration of almost all Google Marketing services like e.g. [Google Tag Manager][gdev-tm].

The library will be integrated through [gatsby-plugin-google-gtag][gh-gb-p-ga-tag].

## Tasks

- [x] Install required packages:
  - [gatsby-plugin-google-gtag][npm-gp-gtag]
- [x] Implement required internal constants.
- [x] Implement the plugin configuration.

[g-sup-anonip]: https://support.google.com/analytics/answer/2763052
[gh-gb-p-ga-tag]: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-gtag
[gh-86]: https://github.com/arcticicestudio/nord-docs/issues/86
[ga-mark]: https://marketingplatform.google.com/about/analytics
[gdev-ga-gtag]: https://developers.google.com/analytics/devguides/collection/gtagjs
[gdev-tm]: https://developers.google.com/tag-manager
[wiki-a]: https://en.wikipedia.org/wiki/Analytics
[wiki-s]: https://en.wikipedia.org/wiki/Statistics
[wiki-dnt]: https://en.wikipedia.org/wiki/Do_Not_Track
[npm-gp-gtag]: https://www.npmjs.com/package/gatsby-plugin-google-gtag
