### ISSUE TITLE
Gatsby Plugin "Web App Manifest"

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-docs#91]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/50234314-aee94d80-03b5-11e9-8eda-e56b9b632b22.png" width="20%" /></p>

This issue documents the integration of [gatsby-plugin-manifest][npm-gpm] that adds support for generating and shipping a [web app (PWA) `manifest.webmanifest`][mdn-web-mf]. It allows users to save _Nord Docs_ as web application to their desktops / task bars and smartphone home screens so it behaves similar to native apps.

See the great Google Developer documentation about [the web app manifest][gdev-fund-wamf] and the [official W3 Web APp Manifest specification][w3-spec-mf].

Note that is **recommended to use this plugin together with** [gatsby-plugin-offline][npm-gpo] (#93), but ensure that **this plugin is listed before the offline plugin** so that it can cache the created `manifest.webmanifest` file!

## Tasks

- [x] Install required package(s):
  - [gatsby-plugin-manifest][npm-gpm]
- [x] Create the source Nord logo _favicon_ image in resized (2000x2000) SVG format.
- [x] Implement the plugin configuration.

[gdev-fund-wamf]: https://developers.google.com/web/fundamentals/web-app-manifest
[mdn-web-mf]: https://developer.mozilla.org/en-US/docs/Web/Manifest
[npm-gpm]: https://www.npmjs.com/package/gatsby-plugin-manifest
[npm-gpo]: https://www.npmjs.com/package/gatsby-plugin-offline
[w3-spec-mf]: https://www.w3.org/TR/appmanifest
